### ISSUE TITLE
Github Issues, Folder-Structure and Github Revamp.

### ISSUE THREAD

**Issue by TrainDoctor** [expanded-mod-team/RL-Expanded-Rewrite#82]
- [x] Temporarily delete ``release`` branch until ``develop`` has been "stabilized"
  - "stabilized" meaning the github issue templates are added to it and it's file structure matches that of #80 
- [x] Github issue templates added to ``develop`` branch (via PR #83)
- [x] Folder structure of ``develop`` branch matches #80
- [x] PR #83 reviewed and merged.
- [x] Restore ``release`` branch after ``develop`` has been "stabilized"
- [x] Remove ``master`` branch after release is added back to repository
  - ``release`` branch will serve as mainline-protected branch
- [x] (?) Remove all stale/unused branches such as ``img-test`` etc.

**Comment by TrainDoctor** [comment]
All goals of this issue accomplished. Closed and locked
